# Generated by Django 3.1.7 on 2021-07-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDischargeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=100)),
                ('assignDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptom', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField(null=True)),
                ('releaseDate', models.DateField(null=True)),
                ('DaySpend', models.PositiveIntegerField(null=True)),
                ('roomCharge', models.PositiveIntegerField(null=True)),
                ('medicineCost', models.PositiveIntegerField(null=True)),
                ('doctorFee', models.PositiveIntegerField(null=True)),
                ('otherCharges', models.PositiveIntegerField(null=True)),
                ('total', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
