# Generated by Django 3.1.7 on 2021-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_patientdischargedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetail',
            name='patientName',
            field=models.CharField(max_length=40),
        ),
    ]
