# Generated by Django 3.1.7 on 2021-08-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210805_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetail',
            name='patientName',
            field=models.CharField(max_length=40),
        ),
    ]
